### ISSUE TITLE
你好，流体这个我专门判断碰撞？

### ISSUE THREAD

**Issue by hjx503838528** [caogtaa/CCTricks#24]
我需求是流体进入某个刚体里面 能判断就行。目前demo不知道怎么下手判断碰撞

**Comment by caogtaa** [comment]
每个粒子的坐标都是能拿到的，可以结合刚体本身的包围盒判断。
> particles.GetPositionBuffer()
要注意映射到CC的坐标系，可参考`MetaBallsAssembler.ts`。

或许有直接用box2d接口做判断的方法，但是我没研究过。
